# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_name', models.CharField(default='\u6e38\u5ba2', max_length=32)),
                ('content', models.TextField(max_length=100, null=True)),
                ('sex', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
