# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='true_name',
            field=models.CharField(default='\u6211\u662f\u8c01', max_length=32),
        ),
    ]
