# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20180422_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='content',
            field=models.TextField(default='\u8fd9\u4e2a\u4eba\u5f88\u61d2\uff0c\u4ec0\u4e48\u90fd\u6ca1\u7559\u4e0b', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='sex',
            field=models.CharField(default='\u5973', max_length=10),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='true_name',
            field=models.CharField(default='\u5929\u5730\u4e00\u53f7', max_length=32),
        ),
    ]
