# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20180422_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
