# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20180422_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='content',
            field=models.TextField(default='\u8fd9\u4e2a\u4eba\u5f88\u61d2\uff0c\u4ec0\u4e48\u90fd\u6ca1\u7559\u4e0b~~~', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='image',
            field=models.CharField(default='image/girl.jpg', max_length=100),
        ),
    ]
