# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20180429_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u722c\u866b\u4efb\u52a1', max_length=32)),
                ('general', models.CharField(max_length=32)),
                ('remark', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.UserInformation')),
            ],
        ),
    ]
