# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
