# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.IntegerField(),
        ),
    ]
