# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='crawl_time',
            field=models.CharField(default='2018-05-09 23:15:38.615000', max_length=100),
        ),
    ]
