# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0012_auto_20180518_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='time',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
